// <auto-generated />
using BackEndFinalProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndFinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201224192346_CreateSliderTableFirstMigrate")]
    partial class CreateSliderTableFirstMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEndFinalProject.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "slider3.jpg",
                            Subtitle = "I must explain to you how all this mistaken idea of denouncing pleasure and prsing pain was born and I will give you a complete account of the system",
                            Title = "<h3>EDUCATION MAKES </h3><h2> PROPER HUMANITY </h2>"
                        },
                        new
                        {
                            Id = 2,
                            Image = "slider2.jpg",
                            Subtitle = "I must explain to you how all this mistaken idea of denouncing pleasure and prsing pain was born and I will give you a complete account of the system",
                            Title = "<h3>EDUCATION MAKES </h3><h2> PROPER HUMANITY </h2>"
                        },
                        new
                        {
                            Id = 3,
                            Image = "slider1.jpg",
                            Subtitle = "I must explain to you how all this mistaken idea of denouncing pleasure and prsing pain was born and I will give you a complete account of the system",
                            Title = "<h3>EDUCATION MAKES </h3><h2> PROPER HUMANITY </h2>"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
